import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RQProviders from "./components/ReactQueryProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokemon Pokemon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-yellow-500 relative mx-auto`}>
        <RQProviders>{children}</RQProviders>
      </body>
    </html>
  );
}
